#ifndef __IPC_EVENT_DEF_H__
#define __IPC_EVENT_DEF_H__

#include "fly_types.h"

#define EVT_MODE_GLOBAL					0x00
#define EVT_MODE_ANDROID				0x01
#define EVT_MODE_POWER					0x02
#define EVT_MODE_STATUS         0x03
#define EVT_MODE_KEY            0x04
#define EVT_MODE_CHIP           0x05
#define EVT_MODE_ACC            0x06
#define EVT_MODE_MCU_STATUS     0x07
#define EVT_MODE_CAR_COMMON			0x09
#define EVT_MODE_CAR_TYPE				0x0A
#define EVT_MODE_CARBACK        0x0B
#define EVT_MODE_SCREEN_BRIGHTNESS 0x0C
#define EVT_MODE_PANELLED       0x0D
#define EVT_MODE_CAN            0x0E
#define EVT_MODE_MISC           0x0F

#define EVT_MODE_AUDIO					0x10
#define EVT_MODE_RADIO					0x11
#define EVT_MODE_AUDIOAMPLIFIER	0x12
#define EVT_MODE_EBOX						0x13

#define EVT_MODE_CONFIGFILE     0x14
#define EVT_MODE_CAR_BCM				0x15

#define EVT_MODE_DEBUGDEMO          0x18

/* #define EVT_MODE_MAX_NUM		64 --> 0x40 */
#define EVT_MODE_MAX			EVT_MODE_MAX_NUM

/*---------------------------------------------------------------------------*/


#define EVT(_MODE_, _OFFSET_)			(((_MODE_) << 24) + (_OFFSET_))


// MODE: GLOBAL GET
#define EVT_GET_GLOBAL_MSG_MIN			EVT(EVT_MODE_GLOBAL, 0x000000)
#define EVT_GET_GLOBAL_MSG_MAX			EVT(EVT_MODE_GLOBAL, 0xFFFFFF)

/* MODE: GLOBAL SET */
#define EVT_SET_GLOBAL_MSG_MIN			EVT(EVT_MODE_GLOBAL, 0x000000)
#define EVT_SET_GLOBAL_CLR_SLEEP		EVT(EVT_MODE_GLOBAL, 0x000000)
#define EVT_SET_GLOBAL_CLR_ACC			EVT(EVT_MODE_GLOBAL, 0x000001)
#define EVT_SET_GLOBAL_SYSTEM_INIT_FINISH   EVT(EVT_MODE_GLOBAL, 0x000002)
#define EVT_SET_GLOBAL_STANDBY			EVT(EVT_MODE_GLOBAL, 0x000003)
#define EVENT_SET_GLOBAL_CLR_SYSTEM_RESET		EVT(EVT_MODE_GLOBAL, 0x000004)
#define EVT_SET_GLOBAL_HAL_CONFIG_CARTYPE   EVT(EVT_MODE_GLOBAL, 0x000005)
#define EVT_SET_GLOBAL_USER_CONFIG_CARTYPE 	               EVT(EVT_MODE_GLOBAL, 0x000006)
#define EVT_SET_GLOBAL_PASSWORDCODE         EVT(EVT_MODE_GLOBAL, 0x000007)
#define EVT_SET_GLOBAL_PERIOD_DEBUG			EVT(EVT_MODE_GLOBAL, 0x000008)
#define EVT_SET_GLOBAL_ENTER_RECOVERY         EVT(EVT_MODE_GLOBAL, 0x000009)
#define EVT_SET_GLOBAL_ENTER_STANDBYMODE    EVT(EVT_MODE_GLOBAL, 0x00000A)
#define EVT_SET_GLOBAL_QUIT_STANDBYMODE    EVT(EVT_MODE_GLOBAL, 0x00000B)

#define EVT_SET_GLOBAL_SYSTEM_READY_TO_RECEIVE_STATUS   EVT(EVT_MODE_GLOBAL, 0x000010)
#define EVT_SET_GLOBAL_ANDROID_RUNNING_STATUS			EVT(EVT_MODE_GLOBAL, 0x000011)

#define EVT_SET_GLOBAL_BATTERY_VOLTAGE					EVT(EVT_MODE_GLOBAL, 0x000050)
#define EVT_SET_GLOBAL_PING_CLEAR								EVT(EVT_MODE_GLOBAL, 0x000051)
#define EVT_SET_GLOBAL_ENTERRECOVRY								EVT(EVT_MODE_GLOBAL, 0x000052)

#define EVT_SET_GLOBAL_MSG_MAX			EVT(EVT_MODE_GLOBAL, 0xFFFFFF)


/* MODE: ANDOIRD SET */
#define EVT_SET_ANDROID_MSG_MIN			EVT(EVT_MODE_ANDROID, 0x000000)
#define EVT_SET_ANDROID_SEND_COMM_MSG	EVT(EVT_MODE_ANDROID, 0x000000)

#define EVT_SET_ANDROID_MSG_MAX			EVT(EVT_MODE_ANDROID, 0xFFFFFF)


/*******************************************************************************/

/* MODE: POWER SET */
#define EVT_SET_POWER_MSG_MIN			EVT(EVT_MODE_POWER, 0x000000)
#define EVT_SET_POWER_CAN_WORK_MODE		EVT(EVT_MODE_POWER, 0x000000)
#define EVT_SET_POWER_MANAGE_POWER		EVT(EVT_MODE_POWER, 0x000001)
#define EVT_SET_POWER_BT_POWER          EVT(EVT_MODE_POWER, 0x000002)
#define EVT_SET_POWER_CARBACK_CAMERA_BY_STARTUP    EVT(EVT_MODE_POWER, 0x000003)
#define EVT_SET_POWER_CARBACK_CAMERA_BY_CONTROL    EVT(EVT_MODE_POWER, 0x000004)
#define EVT_SET_POWER_APPLY_STEP         EVT(EVT_MODE_POWER, 0x000005)
#define EVT_SET_POWER_ANDROID           EVT(EVT_MODE_POWER, 0x000006)
#define EVT_SET_POWER_SCREEN_RESET      EVT(EVT_MODE_POWER, 0x000007)

#define EVT_SET_POWER_USER_RESET_MSG		EVT(EVT_MODE_POWER, 0x000020)
#define EVT_SET_POWER_RESET_WAIT_WAITING 	EVT(EVT_MODE_POWER, 0x000021)
#define EVT_SET_POWER_RESET_WAIT_FINISH 	EVT(EVT_MODE_POWER, 0x000022)

#define EVT_SET_POWER_SLEEP_SHORT_KEY_MSG	EVT(EVT_MODE_POWER, 0x000030)
#define EVT_SET_POWER_SLEEP_LONG_KEY_MSG	EVT(EVT_MODE_POWER, 0x000031)
#define EVT_SET_POWER_SYSTEM_RESET_KEY_MSG	EVT(EVT_MODE_POWER, 0x000032)

#define EVT_SET_POWER_MSG_MAX			EVT(EVT_MODE_POWER, 0xFFFFFF)

/* MODE: POWER GET */
#define EVT_GET_POWER_MSG_MIN			EVT(EVT_MODE_POWER, 0x000000)
#define EVT_GET_POWER_ANDROIDPOWER_CONTROL_STEP    EVT(EVT_MODE_POWER, 0x000001)
#define EVT_GET_GLOBAL_BATTERY_VOLTAGE  EVT(EVT_MODE_POWER, 0x000002)
#define EVT_GET_GLOBAL_BATTERY_MODE  		EVT(EVT_MODE_POWER, 0x000003)
#define EVT_GET_GLOBAL_ENTER_RECOVER  		EVT(EVT_MODE_POWER, 0x000004)


#define EVT_GET_POWER_MSG_MAX			EVT(EVT_MODE_POWER, 0xFFFFFF)

/*******************************************************************************/

/* MODE: STATUS GET */
#define EVT_GET_STATUS_MSG_MIN			EVT(EVT_MODE_STATUS, 0x000000)
#define EVT_GET_IOBRAKE_STATUS          EVT(EVT_MODE_STATUS, 0x000000)
#define EVT_GET_BRAKE_STATUS            EVT(EVT_MODE_STATUS, 0x000001)
#define EVT_GET_STATUS_MSG_MAX			EVT(EVT_MODE_STATUS, 0xFFFFFF)

/* MODE: STATUS SET */
#define EVT_SET_STATUS_MSG_MIN			EVT(EVT_MODE_STATUS, 0x000000)
#define EVT_SET_BRAKE_STATUS            EVT(EVT_MODE_STATUS, 0x000000)
#define EVT_SET_SEND_BRAKE_STATUS       EVT(EVT_MODE_STATUS, 0x000001)
#define EVT_SET_STATUS_MSG_MAX			EVT(EVT_MODE_STATUS, 0xFFFFFF)


/*******************************************************************************/

/* MODE: EVT_MODE_KEY GET */
#define EVT_GET_MODE_KEY_MIN			   EVT(EVT_MODE_KEY, 0x000000)
#define EVT_SET_CAN_KEY		           EVT(EVT_MODE_KEY, 0x000000)
#define EVT_SET_CAN_ABS_KEY          EVT(EVT_MODE_KEY, 0x000001)

#define EVT_GET_MODE_KEY_MAX			   EVT(EVT_MODE_KEY, 0xFFFFFF)



/* MODE: EVT_MODE_KEY SET */

#define EVT_GET_MODE_KEY_MIN			   EVT(EVT_MODE_KEY, 0x000000)
#define EVT_GET_CAN_KEY              EVT(EVT_MODE_KEY, 0x000000)
#define EVT_GET_MODE_KEY_MAX			   EVT(EVT_MODE_KEY, 0xFFFFFF)


/******************************************************************************/


/* MODE: ACC GET */
#define EVT_GET_ACC_MSG_MIN			EVT(EVT_MODE_ACC, 0x000000)
#define EVT_GET_ACC_IOACC_STATUS        EVT(EVT_MODE_ACC, 0x000000)
#define EVT_GET_ACC_STATUS          EVT(EVT_MODE_ACC, 0x000002)
#define EVT_GET_ACC_MSG_MAX			EVT(EVT_MODE_ACC, 0xFFFFFF)


/* MODE: ACC SET */
#define EVT_SET_ACC_MSG_MIN			EVT(EVT_MODE_ACC, 0x000000)
#define EVT_SET_ACC_STATUS   EVT(EVT_MODE_ACC, 0x000000)
#define EVT_SET_ACC_MSG_MAX			EVT(EVT_MODE_ACC, 0xFFFFFF)

/*******************************************************************************/

/* MODE: CHIP GET */
#define EVT_GET_CHIP_MSG_MIN			EVT(EVT_MODE_CHIP, 0x000000)
#define EVT_GET_CHIP_BOOTMODE           EVT(EVT_MODE_CHIP, 0x000000)
#define EVT_GET_CHIP_MSG_MAX			EVT(EVT_MODE_CHIP, 0xFFFFFF)


/* MODE: CHIP SET */
#define EVT_SET_CHIP_MSG_MIN			EVT(EVT_MODE_CHIP, 0x000000)
#define EVT_SET_CHIP_RESET              EVT(EVT_MODE_CHIP, 0x000000)
#define EVT_SET_CHIP_FORBID_CANWAKEUP   EVT(EVT_MODE_CHIP, 0x000001)
#define EVT_SET_CHIP_TIMER1_FANDUTYCYCLE   EVT(EVT_MODE_CHIP, 0x000002)
#define EVT_SET_CHIP_MSG_MAX			EVT(EVT_MODE_CHIP, 0xFFFFFF)

/*******************************************************************************/

/* MODE: CAR CAR_COMMON GET */
#define EVT_GET_CAR_COMMON_MSG_MIN		                EVT(EVT_MODE_CAR_COMMON, 0x000000)
#define EVT_GET_CAR_COMMON_LIGHT_BY_CAN                 EVT(EVT_MODE_CAR_COMMON, 0x000001)
#define EVT_GET_CAR_COMMON_CANLIGHT_PWM_DUTYCYCLE_VALUE    EVT(EVT_MODE_CAR_COMMON, 0x000003) //表示车灯CAN协议中的占空比的数据
#define EVT_GET_CAR_COMMON_ACC_BY_CAN                   EVT(EVT_MODE_CAR_COMMON, 0x000004)
#define EVT_GET_CAR_COMMON_MSG_MAX		                EVT(EVT_MODE_CAR_COMMON, 0xFFFFFF)


/* MODE: CAR CAR_COMMON SET */
#define EVT_SET_CAR_COMMON_MSG_MIN		                EVT(EVT_MODE_CAR_COMMON, 0x000000)
#define EVT_SET_CAR_COMMON_BREAK_STATUS                 EVT(EVT_MODE_CAR_COMMON, 0x000000)
#define EVT_SET_CAR_COMMON_LIGHT_BY_CAN                 EVT(EVT_MODE_CAR_COMMON, 0x000001)
#define EVT_SET_CAR_COMMON_CANLIGHT_PWM_DUTYCYCLE_VALUE    EVT(EVT_MODE_CAR_COMMON, 0x000003) //表示车灯CAN协议中的占空比的数据
#define EVT_SET_CAR_COMMON_ACC_BY_CAN                   EVT(EVT_MODE_CAR_COMMON, 0x000004)
#define EVT_SET_CAR_COMMON_MSG_MAX		                EVT(EVT_MODE_CAR_COMMON, 0xFFFFFF)

/*******************************************************************************/

/* MODE: CAR_TYPE GET */
#define EVT_GET_CAR_TYPE_MSG_MIN	    EVT(EVT_MODE_CAR_TYPE, 0x000000)

#define EVT_GET_CAR_TYPE_SPECIAL        EVT(EVT_MODE_CAR_TYPE, 0x00000F)

#define EVT_GET_CAR_TYPE_MSG_MAX		EVT(EVT_MODE_CAR_TYPE, 0xFFFFFF)


/* MODE: CAR_TYPE SET */
#define EVT_SET_CAR_TYPE_MSG_MIN		EVT(EVT_MODE_CAR_TYPE, 0x000000)
#define EVT_SET_CAR_TYPE_PROTOCOL       EVT(EVT_MODE_CAR_TYPE, 0x000000)

#define EVT_SET_CAR_TYPE_SPECIAL        EVT(EVT_MODE_CAR_TYPE, 0x00000F)
#define EVT_SET_CAR_TYPE_MSG_MAX		EVT(EVT_MODE_CAR_TYPE, 0xFFFFFF)

/*******************************************************************************/

/* MODE: CARBACK GET */
#define EVT_GET_CARBACK_MSG_MIN			EVT(EVT_MODE_CARBACK, 0x000000)
#define EVT_GET_CARBACK_ADC_STATUS      EVT(EVT_MODE_CARBACK, 0x000000)
#define EVT_GET_CARBACK_CAN_STATUS      EVT(EVT_MODE_CARBACK, 0x000001)
#define EVT_GET_CARBACK_STATUS          EVT(EVT_MODE_CARBACK, 0x000002)
#define EVT_GET_CARBACK_MSG_MAX			EVT(EVT_MODE_CARBACK, 0xFFFFFF)


/* MODE: CARBACK SET */
#define EVT_SET_CARBACK_MSG_MIN			EVT(EVT_MODE_CARBACK, 0x000000)
#define EVT_SET_CARBACK_ADC             EVT(EVT_MODE_CARBACK, 0x000000)
#define EVT_SET_CARBACK_CAN             EVT(EVT_MODE_CARBACK, 0x000001)
#define EVT_SET_CARBACK_CHANNELPROTOCOL_SENDSUCCESS   EVT(EVT_MODE_CARBACK, 0x000002)
#define EVT_SET_CARBACK_MSG_MAX			EVT(EVT_MODE_CARBACK, 0xFFFFFF)

/*******************************************************************************/
/* MODE: EVT_MODE_SCREEN_BRIGHTNESS GET */
#define EVT_GET_SCREEN_BRIGHTNESS_MSG_MIN				EVT(EVT_MODE_SCREEN_BRIGHTNESS, 0x000000)
#define EVT_GET_SCREEN_BRIGHTNESS_PWMDUTYCYCLE_VALUE	EVT(EVT_MODE_SCREEN_BRIGHTNESS, 0x000000)
#define EVT_GET_SCREEN_BRIGHTNESS_MSG_MAX				EVT(EVT_MODE_SCREEN_BRIGHTNESS, 0xFFFFFF)

/* MODE: EVT_MODE_SCREEN_BRIGHTNESS SET */
#define EVT_SET_SCREEN_BRIGHTNESS_MSG_MIN				EVT(EVT_MODE_SCREEN_BRIGHTNESS, 0x000000)
#define EVT_SET_SCREEN_BRIGHTNESS_PROTOCOL				EVT(EVT_MODE_SCREEN_BRIGHTNESS, 0x000000)
#define EVT_SET_SCREEN_BRIGHTNESS_DIRTECT				EVT(EVT_MODE_SCREEN_BRIGHTNESS, 0x000001)
#define EVT_SET_SCREEN_BRIGHTNESS_BRIGHTNESS_FIX		EVT(EVT_MODE_SCREEN_BRIGHTNESS, 0x000002)
#define EVT_SET_SCREEN_BRIGHTNESS_BRIGHTNESS_PWM		EVT(EVT_MODE_SCREEN_BRIGHTNESS, 0x000003)
#define EVT_SET_SCREEN_BRIGHTNESS_CARBACK		        EVT(EVT_MODE_SCREEN_BRIGHTNESS, 0x000004)
#define EVT_SET_SCREEN_BRIGHTNESS_MSG_MAX				EVT(EVT_MODE_SCREEN_BRIGHTNESS, 0xFFFFFF)

/*******************************************************************************/
/* MODE: PANELLED GET */
#define EVT_GET_PANELLED_MSG_MIN	                    EVT(EVT_MODE_PANELLED, 0x000000)
#define EVT_GET_PANELLED_BRIGHTNESS_PWMDUTYCYCLE_VALUE	EVT(EVT_MODE_PANELLED, 0x000000)
#define EVT_GET_PANELLED_MSG_MAX		                EVT(EVT_MODE_PANELLED, 0xFFFFFF)


/* MODE: PANELLED SET */
#define EVT_SET_PANELLED_MSG_MIN		        EVT(EVT_MODE_PANELLED, 0x000000)
#define EVT_SET_PANELLED_FLASH_FOR_RESET_SYSTEM	EVT(EVT_MODE_PANELLED, 0x000000)
#define EVT_SET_PANELLED_BRIGHTNESS_PARAMETER   EVT(EVT_MODE_PANELLED, 0x000001)
#define EVT_SET_PANELLED_MSG_MAX		        EVT(EVT_MODE_PANELLED, 0xFFFFFF)

/*******************************************************************************/
/* MODE: CAN GET */
#define EVT_GET_CAN_MSG_MIN	                    EVT(EVT_MODE_CAN, 0x000000)
#define EVT_GET_CAN_MSG_LED_PWM_SETTING			EVT(EVT_MODE_CAN, 0x000010)
#define EVT_GET_CAN_MSG_MAX		                EVT(EVT_MODE_CAN, 0xFFFFFF)

/* MODE: CAN SET */
#define EVT_SET_CAN_MSG_MIN	                    EVT(EVT_MODE_CAN, 0x000000)
#define EVT_SET_CAN_SEND_DATA_TO_BUS            EVT(EVT_MODE_CAN, 0x000000)
#define EVT_SET_CAN_DASH_BOARD_INFO				EVT(EVT_MODE_CAN, 0x000001)
#define EVT_SET_CAN_ANDROID_PROTOCOL			EVT(EVT_MODE_CAN, 0x000002)
#define EVT_SET_CAN_AMPLIFIER_INFO				EVT(EVT_MODE_CAN, 0x000003)
#define EVT_SET_CAN_KEY_INFO                    EVT(EVT_MODE_CAN, 0x000004)
#define EVT_SET_CAN_EXT_AMP_FOR_RESET_SYSTEM	EVT(EVT_MODE_CAN, 0x000005)
#define EVT_SET_CAN_CARBACK_VIDEOANGLE          EVT(EVT_MODE_CAN, 0x000006)
#define EVT_SET_CAN_MCU_STEERWHEEL_ADCKEY          EVT(EVT_MODE_CAN, 0x000007)
#define EVT_SET_CAN_MCU_PANEL_ADCKEY  				EVT(EVT_MODE_CAN, 0x000008)
#define EVT_SET_CAN_MCU_SPNPAGES						 EVT(EVT_MODE_CAN, 0x000009)
#define EVT_SET_CAN_MSG_MAX		                EVT(EVT_MODE_CAN, 0xFFFFFF)

/*******************************************************************************/
/* MODE: EVT_MODE_MCU_STATUS GET */
#define EVT_GET_MCU_STATUS_MSG_MIN         EVT(EVT_MODE_MCU_STATUS, 0x000000)
#define EVT_GET_MCU_CURRENT_STATUS         EVT(EVT_MODE_MCU_STATUS, 0x000000)
#define EVT_GET_MCU_ANDROID_RUN_STATUS     EVT(EVT_MODE_MCU_STATUS, 0x000001) 
#define EVT_GET_MCU_STATUS_MSG_MAX         EVT(EVT_MODE_MCU_STATUS, 0xFFFFFF)

/* MODE: EVT_MODE_MCU_STATUS SET */
#define EVT_SET_MCU_STATUS_MSG_MIN         EVT(EVT_MODE_MCU_STATUS, 0x000000)
#define EVT_SET_MCU_STATUS_CARCANBUS_SLEEP       EVT(EVT_MODE_MCU_STATUS, 0x000000)
#define EVT_SET_MCU_ANDROID_POWERKEY       EVT(EVT_MODE_MCU_STATUS, 0x000001)
#define EVT_SET_MCU_STATUS_MSG_MAX         EVT(EVT_MODE_MCU_STATUS, 0xFFFFFF)

/*******************************************************************************/

/* MODE: MISC GET */
#define EVT_GET_MISC_MIN				EVT(EVT_MODE_MISC, 0x000000)

#define EVT_GET_MISC_MAX        		EVT(EVT_MODE_MISC, 0xFFFFFF)


/* MODE: MISC SET */
#define EVT_SET_MISC_MSG_MIN			EVT(EVT_MODE_MISC, 0x000000)
#define EVT_SET_MISC_BT_RESET			EVT(EVT_MODE_MISC, 0x000000)
#define EVT_SET_MISC_BT_CE				EVT(EVT_MODE_MISC, 0x000001)
#define EVT_SET_MISC_AUDIO_CHIP_RESET	EVT(EVT_MODE_MISC, 0x000002)

#define EVT_SET_MISC_MAX        		EVT(EVT_MODE_MISC, 0xFFFFFF)

/*******************************************************************************/
/* MODE: EVT_MODE_AUDIO GET */
#define EVT_GET_AUDIO_MSG_MIN			EVT(EVT_MODE_AUDIO, 0x000000)
#define EVT_GET_AUDIO_MSG_MAX			EVT(EVT_MODE_AUDIO, 0xFFFFFF)

/* MODE: EVT_MODE_AUDIO SET */
#define EVT_SET_AUDIO_MSG_MIN			EVT(EVT_MODE_AUDIO, 0x000000)
#define EVT_SET_AUDIO_ANDROID_MSG		EVT(EVT_MODE_AUDIO, 0x000000)
#define EVT_SET_AUDIO_MSG_MAX			EVT(EVT_MODE_AUDIO, 0xFFFFFF)

/*******************************************************************************/
/* MODE: EVT_MODE_RADIO GET */
#define EVT_GET_RADIO_MSG_MIN			EVT(EVT_MODE_RADIO, 0x000000)
#define EVT_GET_RADIO_MSG_MAX			EVT(EVT_MODE_RADIO, 0xFFFFFF)

/* MODE: EVT_MODE_AUDIO SET */
#define EVT_SET_RADIO_MSG_MIN			EVT(EVT_MODE_RADIO, 0x000000)
#define EVT_SET_RADIO_REINIT_MSG		EVT(EVT_MODE_RADIO, 0x000000)
#define EVT_SET_RADIO_ANDROID_MSG		EVT(EVT_MODE_RADIO, 0x000001)
#define EVT_SET_RADIO_MSG_MAX			EVT(EVT_MODE_RADIO, 0xFFFFFF)
/*******************************************************************************/

/* MODE: AUDIOAMPLIFIER GET */
#define EVT_GET_AUDIOAMPLIFIER_MSG_MIN				EVT(EVT_MODE_AUDIOAMPLIFIER, 0x000000)

#define EVT_GET_AUDIOAMPLIFIER_MSG_MAX				EVT(EVT_MODE_AUDIOAMPLIFIER, 0xFFFFFF)
#define EVT_GET_AUDIOAMPLIFIER_MUTE_STATUS			EVT(EVT_MODE_AUDIOAMPLIFIER, 0x000001)
#define EVT_GET_AUDIOAMPLIFIER_STANDBY_STATUS		EVT(EVT_MODE_AUDIOAMPLIFIER, 0x000002)

/* MODE: AUDIOAMPLIFIER SET */
#define EVT_SET_AUDIOAMPLIFIER_MSG_MIN				EVT(EVT_MODE_AUDIOAMPLIFIER, 0x000000)
#define EVT_SET_AUDIOAMPLIFIER_FOR_RESET_SYSTEM		EVT(EVT_MODE_AUDIOAMPLIFIER, 0x000000)
#define EVT_SET_AUDIOAMPLIFIER_MUTE_STATUS			EVT(EVT_MODE_AUDIOAMPLIFIER, 0x000001)
#define EVT_SET_AUDIOAMPLIFIER_STANDBY_STATUS		EVT(EVT_MODE_AUDIOAMPLIFIER, 0x000002)
#define EVT_SET_AUDIOAMPLIFIER_MSG_MAX				EVT(EVT_MODE_AUDIOAMPLIFIER, 0xFFFFFF)

/*******************************************************************************/
/* MODE: EBOX GET */
#define EVT_GET_EBOX_MSG_MIN				EVT(EVT_MODE_EBOX, 0x000000)

#define EVT_GET_EBOX_MSG_MAX				EVT(EVT_MODE_EBOX, 0xFFFFFF)


/* MODE: EBOX SET */
#define EVT_SET_EBOX_MSG_MIN				EVT(EVT_MODE_EBOX, 0x000000)
#define EVT_SET_EBOX_DEVICE_INFO			EVT(EVT_MODE_EBOX, 0x000000)
#define EVT_SET_EBOX_MSG_MAX				EVT(EVT_MODE_EBOX, 0xFFFFFF)

/*******************************************************************************/

/*******************************************************************************/
/* MODE: CONFIGFILE GET */
#define EVT_GET_CONFIGFILE_MSG_MIN				EVT(EVT_MODE_CONFIGFILE, 0x000000)
#define EVT_GET_CONFIGFILE_LPC                  EVT(EVT_MODE_CONFIGFILE, 0x000000)
#define EVT_GET_CONFIGFILE_PANELLIGHT           EVT(EVT_MODE_CONFIGFILE, 0x000001)
#define EVT_GET_CONFIGFILE_FANDUTYCYCLE         EVT(EVT_MODE_CONFIGFILE, 0x000002)
#define EVT_GET_CONFIGFILE_SCREEN_SIZE          EVT(EVT_MODE_CONFIGFILE, 0x000003)
#define EVT_GET_CONFIGFILE_IO_BRAKE_EN			EVT(EVT_MODE_CONFIGFILE, 0x000004)
#define EVT_GET_CONFIGFILE_USE_T123_MODULE		EVT(EVT_MODE_CONFIGFILE, 0x000005)
#define EVT_GET_CONFIGFILE_MSG_MAX				EVT(EVT_MODE_CONFIGFILE, 0xFFFFFF)


/* MODE: CONFIGFILE SET */
#define EVT_SET_CONFIGFILE_MSG_MIN				EVT(EVT_MODE_CONFIGFILE, 0x000000)
#define EVT_SET_CONFIGFILE_MSG_MAX				EVT(EVT_MODE_CONFIGFILE, 0xFFFFFF)

/*******************************************************************************/

/*******************************************************************************/
/* MODE: T123Comm GET */
#define EVT_GET_T123COMM_MSG_MIN				EVT(EVT_MODE_T123COMM, 0x000000)
#define EVT_GET_T123COMM_MSG_MAX				EVT(EVT_MODE_T123COMM, 0xFFFFFF)

/* MODE: T123Comm SET */
#define EVT_SET_T123COMM_MSG_MIN				EVT(EVT_MODE_T123COMM, 0x000000)
#define EVT_SET_T123COMM_OSD_MSG                EVT(EVT_MODE_T123COMM, 0x000000)
#define EVT_SET_T123COMM_VIDEO_MSG              EVT(EVT_MODE_T123COMM, 0x000001)
#define EVT_SET_T123COMM_RGBSIGNAL_CHECK_MSG    EVT(EVT_MODE_T123COMM, 0x000002)
#define EVT_SET_T123COMM_MSG_MAX				EVT(EVT_MODE_T123COMM, 0xFFFFFF)

/*******************************************************************************/

/*******************************************************************************/
/* MODE: T123CommUpdate GET */
#define EVT_GET_T123COMMUPDATE_MSG_MIN				EVT(EVT_MODE_T123UPDATE, 0x000000)
#define EVT_GET_T123COMMUPDATE_MSG_MAX				EVT(EVT_MODE_T123UPDATE, 0xFFFFFF)

/* MODE: T123Comm SET */
#define EVT_SET_T123COMMUPDATE_MSG_MIN				EVT(EVT_MODE_T123UPDATE, 0x000000)
#define EVT_SET_T123COMMUPDATE_UPDATE_MSG           EVT(EVT_MODE_T123UPDATE, 0x000000)
#define EVT_SET_T123COMMUPDATE_MSG_MAX				EVT(EVT_MODE_T123UPDATE, 0xFFFFFF)

/*******************************************************************************/
/* MODE: DebugDemo GET */
#define EVT_GET_DEBUGDEMO_MSG_MIN				EVT(EVT_MODE_DEBUGDEMO, 0x000000)
#define EVT_GET_DEBUGDEMO_MSG_MAX				EVT(EVT_MODE_DEBUGDEMO, 0xFFFFFF)

/* MODE: DebugDemo SET */
#define EVT_SET_DEBUGDEMO_MSG_MIN				EVT(EVT_MODE_DEBUGDEMO, 0x000000)
#define EVT_SET_DEBUGDEMO_OSDDISPLAY            EVT(EVT_MODE_DEBUGDEMO, 0x000000)
#define EVT_SET_DEBUGDEMO_OSD_CAR               EVT(EVT_MODE_DEBUGDEMO, 0x000001)
#define EVT_SET_DEBUGDEMO_OSD_KEY               EVT(EVT_MODE_DEBUGDEMO, 0x000002)
#define EVT_SET_DEBUGDEMO_OSD_IO                EVT(EVT_MODE_DEBUGDEMO, 0x000003)
#define EVT_SET_DEBUGDEMO_OSD_T123              EVT(EVT_MODE_DEBUGDEMO, 0x000004)
#define EVT_SET_DEBUGDEMO_OSD_VERSION           EVT(EVT_MODE_DEBUGDEMO, 0x000005)
#define EVT_SET_DEBUGDEMO_MSG_MAX				EVT(EVT_MODE_DEBUGDEMO, 0xFFFFFF)

/*******************************************************************************/
/* MODE: BcmComm SET */
#define EVT_SET_BCM_MSG_MIN				EVT(EVT_MODE_CAR_BCM, 0x000000)
#define EVT_SET_BCM_LIGHT_LOCK_MSG           		EVT(EVT_MODE_CAR_BCM, 0x000000)
#define EVT_SET_BCM_LIGHT_UNLOCK_MSG           	EVT(EVT_MODE_CAR_BCM, 0x000001)
#define EVT_SET_BCM_ALL_STATUS_REQUEST_MSG			EVT(EVT_MODE_CAR_BCM, 0x000002)
#define EVT_SET_BCM_MSG_MAX				EVT(EVT_MODE_CAR_BCM, 0xFFFFFF)

/*******************************************************************************/
#endif

